---

- name: Check kernel version for docker support
  fail:
    msg: "Kernel version {{ ansible_kernel }} does not meet minimum version ({{ docker_minimal_kernel_version }})."
  when: "{{ ansible_kernel | version_compare(docker_minimal_kernel_version, '<') }}"

- name: Create docker group
  group:
    name: docker
    state: present
    gid: '{{ docker_group_id }}'
    system: yes
  when: docker_create_group == True

- include: setup-Debian.yml
  when: ansible_os_family == "Debian"

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- include: configure.yml
